### ISSUE TITLE
Default config for PMD fails under Gradle 2.3

### ISSUE THREAD

**Issue by DTecheira** [Monits/static-code-analysis-plugin#1]
```
* What went wrong:
Execution failed for task ':commons:pmd'.
> java.lang.IllegalArgumentException: Unable to find referenced rule CommentDefaultAccessModifier; perhaps the rule name is mispelled?
```

**Comment by jsotuyod** [comment]
You are using a local config which includes that rule, which is only available from Gradle 2.4+ (PMD 5.4+). You should either upgrade Gradle, change your local config or use the default config which will not include that rule.
