### ISSUE TITLE
Using the static code analysis plugin causes gradle sync to fail

### ISSUE THREAD

**Issue by Okeanos** [Monits/static-code-analysis-plugin#10]
I just created an empty test project in the up to date Android Studio (2.2.3; macOS 10.11.6; JRE 1.8.0_112 x86_64; local Gradle 2.14.1 as supplied by AS). When I add this plugin to the app's `build.gradle` the following happens on gradle sync process:

```
Error:(2, 0) Could not get unknown property 'default' for configuration container.
```

No other changes have been made to the default gradle file (see below). It does not matter whether the DSL config is included in the build file or not.

Any idea why this happens and/or what the problem is?

```gradle
plugins {
    id 'com.monits.staticCodeAnalysis' version '2.3.3'
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "com.test.androidtestapp"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    androidLint 'com.monits:android-linters:1.3.0'
}
```

**Comment by jsotuyod** [comment]
The problem is the order on which you are applying plugins. The staticCodeAnalysis plugin needs to know what kind of project it's dealing with (Java, Android App or Android Lib) to configure it properly, but since you are applying it first, it can't and fails.

For the time being, just change the order to:

```
apply plugin: 'com.android.application'

plugins {
    id 'com.monits.staticCodeAnalysis' version '2.3.3'
}
```

Some parts of the plugin are already lazy and ok with this, but clearly not all. I'll try to get this fixed for the next release (2.3.4)

**Comment by Okeanos** [comment]
I see … but that causes other problems. Notably, the `plugins {}` statement has to be the first thing in the gradle file according to the specifications:
```
Error:(3, 0) Cause: startup failed:
build file '<snip>': only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed
``` 

A workaround that does work is using the [build script variant](https://github.com/Monits/static-code-analysis-plugin#adding-it-to-your-project) and applying the staticCeAnalysis plugin after the android application one.

**Comment by jsotuyod** [comment]
@Okeanos You are absolutely right.

I'm raising the priority to this. I originally planed to wait to release 2.3.4 until PMD 5.5.3 / PMD 5.6.0 was available (it has too many improvements), but this one is probably big enough for a release on it's own. I'm working on it as we speak.

**Comment by jsotuyod** [comment]
@Okeanos Travis is building to double check my fixes. If everything is good (other than a conscious performance regression on Checkstyle due to the enabling of the results cache), expect a 2.3.4 release later today.

**Comment by jsotuyod** [comment]
@Okeanos 2.3.4 has been released. This issue should now be fixed.

Let me know if you have any further issues.
