### ISSUE TITLE
Honour Gradle offline setting in Android Studio

### ISSUE THREAD

**Issue by barriosnahuel** [Monits/static-code-analysis-plugin#24]
It would be great to stop downloading and check local default location when this setting is on.

**Comment by jsotuyod** [comment]
I've no idea what Android Studio does, but the codebase does honor Gradle's `--offline`

https://github.com/Monits/static-code-analysis-plugin/blob/724b159d869baba6465cad72bd624df03318da4f/src/main/groovy/com/monits/gradle/sca/task/DownloadTask.groovy#L47-L58

**Comment by barriosnahuel** [comment]
Ok, let me check what I've done and after that I will reopen it :)
