### ISSUE TITLE
The findbugs project is now spotbugs

### ISSUE THREAD

**Issue by SMillerDev** [Monits/static-code-analysis-plugin#28]
Will this plugin be making the move to spotbugs as well?

https://github.com/findbugsproject/findbugs#findbugs-is-now-spotbugs

**Comment by jsotuyod** [comment]
@SMillerDev definitely (I'm part of [Spotbugs founding team](https://github.com/orgs/spotbugs/people?utf8=%E2%9C%93&query=jsotuyod) after all).

I'm just wondering if doing it in a major release (report names and locations do change) or in a minor one (it's a drop-in replacement after all...).

I also wonder if we should change the DSL to actually name spotbugs or not... maybe add a new spotbugs config identical to findbugs, and let people opt-in / opt-out as we transition to dropping findbugs in a next major?

Input is welcomed on this issue.

**Comment by SMillerDev** [comment]
Completely forgot to actually answer here. I'd say a major release is in order for this change. Maybe keep the findbugs name as an alias for people who don't want to update, but I think a "new" project is worth a major bump.

**Comment by jsotuyod** [comment]
Gradle 6.0 removed the Findbugs plugin, making SCA incompatible. Moreover, the Spotbugs team provides a community plugin with a very similar DSL. Seems like a nice opportunity to upgrade; but will require a major release from this plugin.

**Comment by jsotuyod** [comment]
This is currently targeted for 3.0 release, currently under development.

**Comment by jsotuyod** [comment]
Already present on develop, soon to be released under 3.0.0
