### ISSUE TITLE
SCA not working

### ISSUE THREAD

**Issue by roliveiravictor** [Monits/static-code-analysis-plugin#34]
Hi, 

My files are referenced under root for a flexible config, gradle wrapper is `4.10.2` ; still, I can't get to run `checkstyle` for example. From readme:

> All tasks, are hooked to be run as part of the check task of the Java Plugin.

Also running `gradle check`, `checkstyle` does not seems to work; I've placed unused imports to make sure that build would fail.

I can't see tasks created under Gradle Tasks UI of Android Studio; Other plugins like `detekt` are working fine.

Would you mind to support me on this? I really enjoyed your plugin =)

```
apply plugin: 'com.monits.staticCodeAnalysis'

buildscript {
    ext {
        ...
        monits_version = '2.6.10'
        gradle_version = '3.3.1'
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:${gradle_version}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.monits:static-code-analysis-plugin:$monits_version"
        ...
    }
}

allprojects {

    repositories {
        google()
        jcenter()
    }

    staticCodeAnalysis {
        findbugs = true
        checkstyle = true
        pmd = true
        cpd = true
        androidLint = true
        ignoreErrors = false

        sourceSetConfig {
            test {
                findbugsExclude = "${project.rootDir}/.findbugs.xml"
                checkstyleRules = "${project.rootDir}/.checkstyle.xml"
                androidLintConfig = "${project.rootDir}/.lint.xml"
                pmdRules = [ "${project.rootDir}/.pmd.xml",
                             "${project.rootDir}/.pmd-android.xml" ]
            }
        }
    }
}

```

**Console**

```
➜  mProject git:(master) ✗ ./gradlew checkstyle                                                                                                                              10/08/19 |11:21AM

FAILURE: Build failed with an exception.

* What went wrong:
Task 'checkstyle' not found in root project 'Shutter Gallery'.

```

**Comment by roliveiravictor** [comment]
I just realized that adding `apply plugin: 'com.monits.staticCodeAnalysis'` to `app.gradle` and `<mobules>.gradle` makes tasks to be generated. Now running `gradle check` everything works. Still, I don't understand why that doesn't fit under `allProjects` config like:

```
allprojects {
    apply plugin: 'com.monits.staticCodeAnalysis'
    ...
}
```

**Output**

```
Failed to apply plugin [class 'org.gradle.api.plugins.BasePlugin']
```

**Comment by jsotuyod** [comment]
@roliveiravictor the problem is `allprojects` includes not only submodules, but the root project itself.

As the root project is neither a Java nor Android project, no analysis tasks can be configured / setup for it.

You should use `subprojects { }` instead if you want to apply it once for all submodules.
